// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8JXSuWJtQyQjr5ObNwx5mLBiR75b2CwE',
    appId: '1:65143409810:web:3cadbf7530c12c41406a4b',
    messagingSenderId: '65143409810',
    projectId: 'chatapptute-acbf5',
    authDomain: 'chatapptute-acbf5-d4c91.firebaseapp.com',
    storageBucket: 'chatapptute-acbf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD_KeXxS3wQONKZPOjxYcMvy_ODv885kY',
    appId: '1:65143409810:android:cb6894c1cd248f89406a4b',
    messagingSenderId: '65143409810',
    projectId: 'chatapptute-acbf5',
    storageBucket: 'chatapptute-acbf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZEBIf8gcfNHNf84brdOHjeSMwBaIoEg',
    appId: '1:65143409810:ios:85701dcd861201a9406a4b',
    messagingSenderId: '65143409810',
    projectId: 'chatapptute-acbf5',
    storageBucket: 'chatapptute-acbf5.appspot.com',
    iosClientId: '65143409810-aj8tijgi9hkf1ilqcjrebop9151ov3qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZEBIf8gcfNHNf84brdOHjeSMwBaIoEg',
    appId: '1:65143409810:ios:450a3368b4ae0c41406a4b',
    messagingSenderId: '65143409810',
    projectId: 'chatapptute-acbf5',
    storageBucket: 'chatapptute-acbf5.appspot.com',
    iosClientId: '65143409810-4vklc6g2ki6l98mb6r8kfgnb6eijqc09.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
